### ISSUE TITLE
breeze-sequelize and outdated dependecies

### ISSUE THREAD

**Issue by KingRial** [Breeze/breeze.server.node#10]
Using the command:
```
npm install breeze-sequelize
```
will install a depreacted sequelize's version:
```
npm WARN deprecated sequelize@2.1.3: critical security fix in v3.0.0
```

I installed an updated sequelize library with the following dependencies:
```
"dependencies": {
    "bluebird": "^2.3.2",
    "breeze-client": "*",
    "lodash": "^3.9.3",
    "mysql": "^2.4.3",
    "node-uuid": "^1.4.1",
    "sequelize": "^3.3.2",
    "toposort": "^0.2.10"
  },
```
So far I haven't met any bug.

Is there any problem about using an updated sequelize libray with breeze-sequelize instead of the old one ?

If not, we should just update the package.json. :+1:

**Comment by istrau2** [comment]
I have the same issue

**Comment by JuHwon** [comment]
+1

**Comment by Wesseldr** [comment]
+1

**Comment by helmutkian** [comment]
+1 

Ran into a related problem. The out-dated version of Sequelize included does not support the 'domain' option for MSSQL necessary for Windows authentication.

**Comment by helmutkian** [comment]
Pull request created: https://github.com/Breeze/breeze.server.node/pull/15

**Comment by steveschmitt** [comment]
But does breeze-sequelize work with 3.13.0 with no other changes to the code?

**Comment by JuHwon** [comment]
I was running my app with an mssql server and the new sequelize version for 1 week without any problems. Sadly i couldnt get the tests running of this repo so i couldnt run the tests withe the modified sequelize version.

**Comment by steveschmitt** [comment]
I just made the update to 3.13.0, and changed some other affected files.  Let me know if you discover any problems.  Thanks!

**Comment by KingRial** [comment]
"Breeze-Sequelize" NPM library ( https://www.npmjs.com/package/breeze-sequelize ) is still not updated.
Current version on NPM: v0.0.14

Using
```
npm install breeze-sequelize
```
will still install a deprecated sequelize's version.

**Comment by steveschmitt** [comment]
Yes, it was only updated in github earlier.  I finally updated the npm package (it's v0.0.16 now).  Please get it and try it out.  Thanks for your patience.
