### ISSUE TITLE
breeze-sequelize and "parseUrl" method

### ISSUE THREAD

**Issue by KingRial** [Breeze/breeze.server.node#14]
Hello everyone.

I'm pretty new to the "Breeze" library so I could be doing something wrong.
However, while using a server based on breeze-sequelize + express, I met a problem with the "parseUrl" method of "SequelizeQuery.json.js"

For some reasons I still have to investigate, all my Breeze requests where built as a collection of URL's queries instead as a single URL's query describing the single breeze request.

This means I had to modify the breeze-sequelize library to obtain a correct response from the solution:
https://github.com/KingRial/breeze.server.node/commit/00eee008cb29e6a489f9248592150153708000a1

As you ca see "parsedUrl.query" property is already exposed as a javascript object and it doesn't need to be converted with the previous operations ( see the previous code's comments for details ).

I don't know if the current library is outdated ( as its dependencies are ) or if I am using the library in the wrong way, but I thought this could be usefull to know :)

**Comment by JuHwon** [comment]
Im not 100% sure though don't think this is a problem of the breeze-sequelize package.

How does your request exactly look like? 
How is your breeze `uriBuilder` configured? 

I had some problems with the url parsing too until i configured my breeze client `uriBuilder` like this:
```
breeze.core.config.initializeAdapterInstance('uriBuilder', 'json');
``` 
Here is also an angular [example](https://github.com/Breeze/breeze.js.samples/blob/master/node/tempHire/client/app/services/entitymanagerprovider.js).

I got many help from the breeze.js.samples [repository](https://github.com/Breeze/breeze.js.samples) when i started my first breeze implementations.

**Comment by KingRial** [comment]
You were right.
I was just using the uriBuilder in the wrong way.

Now everything is set and I can freely use breeze.
Thanks!
