### ISSUE TITLE
When will you bump the npm breeze-sequelize version?

### ISSUE THREAD

**Issue by jnis77diver** [Breeze/breeze.server.node#16]
The issue where the autoGeneratedKeyType Identity in MetadataMapper was not correctly auto-incrementing in Postgres (and perhaps MySQL as well) has been fixed and merged in this PR. https://github.com/Breeze/breeze.server.node/commit/e758094d882b91cd28538523bad16664c4019c7e 

Any idea when this will be rolled out to npm?
I would love to be able to use this on a production app.

**Comment by steveschmitt** [comment]
I just published [breeze-sequelize](https://www.npmjs.com/package/breeze-sequelize) v 0.0.16, supporting the latest sequelize (3.14).  Please give it a try.
Thanks!
