### ISSUE TITLE
CRUD within sequelize transactions

### ISSUE THREAD

**Issue by istrau2** [Breeze/breeze.server.node#18]
It looks like currently updates, inserts and deletes occur within sequelize transactions. Here is example output:

```
Executing (1b4b53e2-fca8-4b8d-9dd8-fee248b08e82): START TRANSACTION;
Executing (1b4b53e2-fca8-4b8d-9dd8-fee248b08e82): SET SESSION TRANSACTION ISOLATION LEVEL REPEATABLE READ;
Executing (1b4b53e2-fca8-4b8d-9dd8-fee248b08e82): SET autocommit = 1;
Executing (default): UPDATE "v_account" SET "name"='Account Name 1' WHERE "account_pkey" = '8'
Executing (1b4b53e2-fca8-4b8d-9dd8-fee248b08e82): COMMIT;
```

So first a question:
Why does the update line (this happens on inserts and deletes as well though) occur with ```(default)``` while the others occur with ```(1b4b53e2-fca8-4b8d-9dd8-fee248b08e82)```
I looked through the sequelize code and it seems this is a client uuid. What effect does the uuid have and why is it not on the actual CRUD?

Additionally, I am trying to add custom ddl before every db operation. I tried this:
```javascript
var saveHandler = b_sHelper.sequelizeSaveHander(req);
    saveHandler.beforeSaveEntities = function(){
        this.sequelizeManager.sequelize.query("CREATE TEMP TABLE global_variable ON COMMIT DROP AS SELECT 'LOGIN_PKEY'::text AS name, '" + req.user +"'::text AS value;")
    };
    saveHandler.save();
```
and it works but the 'create temp table' line is also executed as (default):

```
Executing (a4fa2f58-d1b8-443d-afd9-9e4fdd1c7640): START TRANSACTION;
Executing (a4fa2f58-d1b8-443d-afd9-9e4fdd1c7640): SET SESSION TRANSACTION ISOLATION LEVEL REPEATABLE READ;
Executing (a4fa2f58-d1b8-443d-afd9-9e4fdd1c7640): SET autocommit = 1;
Executing (default): CREATE TEMP TABLE global_variable ON COMMIT DROP AS SELECT 'LOGIN_PKEY'::text AS name, '44'::text AS value;
Executing (default): UPDATE "v_account" SET "name"='PREMIER2' WHERE "account_pkey" = '8'
Executing (a4fa2f58-d1b8-443d-afd9-9e4fdd1c7640): COMMIT;
```

How can I do the same thing for reads (i.e. execute selects within a transaction and execute some ddl before the select in the transaction with some beforeQueryEntities method). If there is no such way, can it be added?

**Comment by istrau2** [comment]
Ok, update on this.

I have a working implementation of  selects within transaction (including the beforeQueryEntities method). I changed SequelizeQuery.executeRaw below:

```javascript
SequelizeQuery.prototype.executeRaw = function(options) {
  var self = this;
  var model = self.sequelizeManager.resourceNameSqModelMap[self.entityQuery.resourceName];
  var methodName = self.entityQuery.inlineCountEnabled ? "findAndCountAll" : "findAll";
  options = options || {};

  return (function(){
      if (options.useTransaction)
          return self.sequelizeManager.sequelize.transaction()
          .then(function(trans) {
              self.transaction = trans;
              self.sqQuery.transaction = trans;
          });
      else
          return Promise.resolve();
  })()
  .then(function() {
          if (options.beforeQueryEntities)
            return options.beforeQueryEntities.call(self);
          else
            return Promise.resolve();
  })
  .then(function() {
      return model[methodName].call(model, self.sqQuery);
  })
  .then(
      function(results){
        if (options.useTransaction)
            self.sqQuery.transaction.commit();
        return results;
    },
      function(e) {
          self.sqQuery.transaction.rollback();
          throw e;
      }
  );
}
```
As you can see it accepts an options parameter in which one can specify ```useTransaction``` and ```beforeQueryEntities```.

I also had to change ```SequelizeQuery.execute``` so that it could accept options and pass them on:

```javascript
SequelizeQuery.prototype.execute = function(options) {
  var that = this;
  return this.executeRaw(options).then(function(r) {
    var result = that._reshapeResults(r);
    return Promise.resolve(result);
  })
}
```
Available in the beforeQueryEntities callback is a ```this``` context that has several properties including sequelizeManager, transaction (if useTransaction is true) and sqQuery.

SequelizeQuery can now be used like so:
```javascript
query.execute({useTransaction: true, beforeQueryEntities: function(){
        return this.sequelizeManager.sequelize.query("CREATE TEMP TABLE global_variable ON COMMIT DROP AS SELECT 'LOGIN_PKEY'::text AS name, '" + user_pkey +"'::text AS value;", {transaction: this.transaction})
    }});
```
which outputs:
```
Executing (61094f86-610d-4f43-8588-49002a14652e): START TRANSACTION;
Executing (61094f86-610d-4f43-8588-49002a14652e): SET SESSION TRANSACTION ISOLATION LEVEL REPEATABLE READ;
Executing (61094f86-610d-4f43-8588-49002a14652e): SET autocommit = 1;
Executing (61094f86-610d-4f43-8588-49002a14652e): CREATE TEMP TABLE global_variable ON COMMIT DROP AS SELECT 'LOGIN_PKEY'::text AS name, '44'::text AS value;
Executing (61094f86-610d-4f43-8588-49002a14652e): SELECT etc...
Executing (61094f86-610d-4f43-8588-49002a14652e): COMMIT;
```
or like this:
```javascript
return query.execute();
```
which outputs:
```
Executing (default): SELECT etc...
```

Let me know if you want me to submit a pull request for this or if you want to just copy the code from here.

Unfortunately, I think this confirms another bug that I suspected which is that the saveHandler.save()
executes its CRUD outside of the transaction as you can see in my first post. As you can see in the first output above, the SELECT happens within the transaction. Additionally, it would be nice to have the transaction available in the beforeSaveEntities callback so that custom sql can be executed within that transaction (as in my implementation).

**Comment by steveschmitt** [comment]
I can just copy the code from here, if that's easiest for you.
Thanks for your work on this!

**Comment by istrau2** [comment]
Yes, that is easier for me. Also, the reason that the inserts, updates and deletes are not made in the transaction is because it is commented out in SequelizeSaveHandler._saveEntityAsync (why is it commented out?):

line 250:
```javascript
// return sqModel.create(entity, trxOptions).then(function(savedEntity) {
      return sqModel.create(entity).then(function(savedEntity) {
```

line 303:
```javascript:
// return sqModel.update(setHash, { where: whereHash }, trxOptions).then(function(infoArray) {
    return sqModel.update(setHash, { where: whereHash }).then(function(infoArray) {
```

line 323:
```javascript:
// return sqModel.destroy({ where: whereHash, limit: 1, transaction: transaction}).then(function() {
    return sqModel.destroy({ where: whereHash, limit: 1}).then(function() {
```

**Comment by istrau2** [comment]
Hey so I submitted a pull request addressing this. Any chance of getting it merged?

**Comment by steveschmitt** [comment]
Yes, I just need to do some more testing and I haven't had time.  I hope to get to it this week.  

Sorry about the delay, and thanks for your patience.

**Comment by steveschmitt** [comment]
Merged!  Thanks again.
