### ISSUE TITLE
Breeze-Mongo 2.0

### ISSUE THREAD

**Issue by Phoscur** [Breeze/breeze.server.node#20]
To work around recent build problem on Node 4.2, I updated my mongodb dependency to 2.0 also.
Now I'm noticing that the current adapter does not read the new/full response from mongodb, and throws "Error: Not Inserted".

Can I expect further work on the breeze-mongo adapter or am I supposed to create my own fork?

**Comment by davideweaver** [comment]
Same issue here. @Phoscur have you found a workaround?

**Comment by Phoscur** [comment]
Change mongoSaveHandler.js:L296 to
```javascript
    if ((!insertedObjects) || insertedObjects.length !== 1 && !insertedObjects.result && !insertedObjects.result.ok) {
```
HTH @davideweaver

**Comment by davideweaver** [comment]
That worked. Thanks

On Dec 30, 2015, at 11:14 PM, Phoscur <notifications@github.com<mailto:notifications@github.com>> wrote:


Change mongoSaveHandler.js:L296 to

    if ((!insertedObjects) || insertedObjects.length !== 1 && !insertedObjects.result && !insertedObjects.result.ok) {

HTH @davideweaver<https://github.com/davideweaver>

**Comment by steveschmitt** [comment]
I don't have a mongodb testbed at the moment, but I have added your fix to mongoSaveHandler.js.

**Comment by Phoscur** [comment]
Is it possible to release the fix as 0.0.7? Do you have any other plans on updating the project?

**Comment by bndr** [comment]
Can you please release the 0.0.7 version to npm?

**Comment by steveschmitt** [comment]
I have just pushed the updated version.  Sorry, I thought that had already been done.
