### ISSUE TITLE
Breeze-sequelize not compatible with BreezeJS v1.5.5

### ISSUE THREAD

**Issue by KingRial** [Breeze/breeze.server.node#24]
Hello everyone,

I'm using breeze-sequelize with BreezeJS v1.5.5 and it seems to be a big incompatibility.

For example if Breeze JS sends the following entity query to the server:
```javascript
new EntityQuery({
   from: 'OBJECT',
   where: {
     'id': { in: [1] }
   },
   orderBy: [ 'id asc' ],
   skip:20,
   take:10,
   inlineCount: true
 })
```

The server receives an GET request similar to:
```
/breeze/OBJECT?$filter=(id%20eq%201)&$orderby=id&$skip=20&$top=10&$inlinecount=allpages
```

All is fine until Breeze-sequelize tries to convert the URL into a JSON Object ( see Line 13 to 19 of class [SequelizeQuery.json.js](https://github.com/Breeze/breeze.server.node/blob/master/breeze-sequelize/src/SequelizeQuery.json.js#L13) )

All my libraries are update to the latest stable version using npm/jspm.

I'm pretty new to Breeze environment and I can't undestand if there is really a incompatibility or I am using Breeze in a bad way.
i can't understand why calling the method "fromUrl" is crashing since I am not the one building the URL itself.
```
Breeze.EntityQuery.fromUrl( sQueryURL, sResourceName );
```

The error is:
```
SyntaxError: Unexpected token $
    at Object.parse (native)
    at Function.EntityQuery.fromUrl (F:\Sources\...\node_modules\breeze-sequelize\SequelizeQuery.json.js:20:24)
...
```
Any idea ?

**Comment by steveschmitt** [comment]
There are two different URI formats that the Breeze client can use to send queries to the server: [OData](http://www.odata.org/documentation/odata-version-3-0/url-conventions/#url5) and [JSON](http://breeze.github.io/doc-js/query-using-json.html).  

The Breeze Sequelize Server only understands the JSON format, so you'll need to configure the client:

    breeze.core.config.initializeAdapterInstance("uriBuilder", "json");

**Comment by KingRial** [comment]
Thanks a lot!
It solved everything.
