### ISSUE TITLE
Sequelize version dependency is outdated and does not support the hasTrigger option

### ISSUE THREAD

**Issue by cocoadventure** [Breeze/breeze.server.node#27]
The sequelize dependency version needs to be at least 3.6.0 to support triggers for MSSQL implementation.

**Comment by steveschmitt** [comment]
Just released [breeze-sequelize](https://www.npmjs.com/package/breeze-sequelize) v0.0.19, which supports sequelize 3.24.x.  I haven't tested it with triggers, though; let me know if you discover any problems.
Thanks.
