### ISSUE TITLE
Calculate dependencies on save changes for self - referencing entities

### ISSUE THREAD

**Issue by iz-iznogood** [Breeze/breeze.server.node#32]
In case of a self - referencing entity (id - parentId hierarchy for example) the insert - update - delete order is important especially if foreign keys are used.
In such cases the saveChanges fails randomly since the processing order is the order the entities where created on the client. 
I tried to solve this by sorting the entities graph in case there is such a dependency.

**Comment by iz-iznogood** [comment]
I have a couple for fixes around this. I did not send them earlier because I did not receive any feedback. I send them over now, these are fixes that I found in production deployments

**Comment by steveschmitt** [comment]
Thanks for your work on this.  Sorry it's taken so long for me to review and merge your pull requests.

**Comment by iz-iznogood** [comment]
Thanks for merging this !!!!
