### ISSUE TITLE
Update npm package to 0.0.9

### ISSUE THREAD

**Issue by PeteMac88** [Breeze/breeze.server.node#41]
Hey, could you please update the published npm package to a newer version to reflect the changes done in the past years? Especially he support for the mongodb v3 library is needed.

**Comment by PeteMac88** [comment]
@steveschmitt @marcelgood

**Comment by PeteMac88** [comment]
@marcelgood  @steveschmitt  Any news here? Would be great to use this repo with newer mongodb driver!

**Comment by steveschmitt** [comment]
Finally published 0.0.9.  Sorry it took so long!
