### ISSUE TITLE
Improve the postgres documentation

### ISSUE THREAD

**Issue by PWKad** [Breeze/breeze.server.node#6]
I struggled with figuring out how to use postgres because I didn't specify the dbConfig properties properly.  Specifically I didn't catch that I needed to set the dialect for quite some time and even now with what I know are valid credentials I'm getting an 'Access Denied' message.  I'm still going through the sequelize documentation to figure out what may be wrong but I would vote up adding some more detailed instructions for postgres with the breeze-sequelize documentation

**Comment by jtraband** [comment]
You are right, we should have made this easier!.  But... we did almost all of our testing on MySQL and haven't spent a lot of time with Postgres.  So, not to turn this around but if you do have any information/gotcha's about using postgres with breeze.server.node, please add comments here, or better yet add a page (via a pull request) to our new breeze docs at breeze.github.io.  I'll make sure it get's edited and posted.

**Comment by PWKad** [comment]
Definitely will do, that's good to know as well because I've assumed it had more testing.  Once I get everything up and running I'll definitely add some to the docs specific to postrgres.

**Comment by PWKad** [comment]
@jtraband From what I can tell the [dbUtils](https://github.com/Breeze/breeze.server.node/blob/93c9f8c05b2bd34b3ad6b0de8ba8a65153827fbb/breeze-sequelize/src/dbUtils.js#L15) is configured to only use MySql - I've been having issues connecting to PostGres but if anyone on the IdeaBlade side gets a chance to confirm that PostGres needs additional setup besides the dialect I'd appreciate the confirmation.

**Comment by PWKad** [comment]
I'm going to close this issue and open issues specifically on what needs to be updated so I can reference them directly from PRs.

**Comment by jtraband** [comment]
Excellent, and thanks for the help!
