### ISSUE TITLE
Docs improperly reference dbConfig

### ISSUE THREAD

**Issue by PWKad** [Breeze/breeze.server.node#7]
The docs mention the dbConfig object should be set this way - 

SequelizeManager(dbConfig, sequelizeOptions): (class constructor)

dbConfig - the configuration object that consists of the following properties:
dbName: The name of the database.
user: The user name to authenticate against the database.
password: The password which is used to authenticate against the database.
sequelizeOptions - as defined in the sequelize documentation here: http://sequelize.readthedocs.org/en/latest/api/sequelize/. The most important of which are:
dialect: The dialect you of the database you are connecting to. One of 'mysql', 'postgres', 'sqlite', 'mariadb', or 'mssql'
port: The port of the relational database. 

But in fact the sequelizeOptions (dialect and port) should be a separate object that gets passed in to the SequelizeManager to load the proper config settings.

**Comment by JuHwon** [comment]
+1. as a breeze/sequelize newb this actually was costing me 1 hour

**Comment by steveschmitt** [comment]
You are right, it was hard to understand.  Fixed now.
