### ISSUE TITLE
dbUtils does not provide a proper connection to any other databases besides mySql

### ISSUE THREAD

**Issue by PWKad** [Breeze/breeze.server.node#8]
dbUtils is specific to mySql connections only.  To support Postgres at the least there needs to be an additional set of utilities or to remove the references to dbUtils from SequelizeManager.js and utils.js

**Comment by steveschmitt** [comment]
@PWKad In commit [59672aa](https://github.com/Breeze/breeze.server.node/commit/59672aaaf2622ec6bd5c22d84e184b2f6e587264) I changed dbUtils to remove the manual connection code.  Instead it just uses Sequelize to connect.  This removes the hard dependency on mysql, and eliminates the database-specific code.  Let me know if causes any problems for you.

**Comment by PWKad** [comment]
Cool I'll be taking a look at this project I was working on again this weekend.  Thanks!
